<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.genbox</groupId>
        <artifactId>GenBox-Agent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>genbox-agent-redis-tool-framework</artifactId>
    <name>genbox-agent-tool-framework</name>
    <description>redis工具组件</description>
    <packaging>pom</packaging>

    <modules>
        <module>genbox-agent-redis-common-framework</module>
        <module>genbox-agent-redis-framework</module>
    </modules>

</project>
